# -*- coding: utf-8 -*-
"""implementation_gillbert_elliot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lEsY6sh4ApGu4VxKSgQ8p55enhmDJmTq
"""

import os
import pandas as pd
import glob
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from fbprophet import Prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error
plt.style.use('fivethirtyeight') # For plots

df = pd.read_csv("./server_client/server_files/Recieved_file.csv")

"""Setting up Dataset where few Samples are dropped"""

df.head()

df = df[df.Datetime != "Datetime"]

df.head()

df = df.reset_index(drop=True)

df.head()

df.dtypes

df['Datetime'] = pd.to_datetime(df['Datetime'],errors='coerce')
df['PJME_MW']= df['PJME_MW'].astype(float)

type(df['Datetime'])

df['delay'].dtypes

df

type(df['PJME_MW'])

df = df.drop(['delay'],axis=1)

df.head()

df.head()

# # Color pallete of PJME Delayed for plotting 
# color_pal = ["#F8766D", "#D39200", "#93AA00",
#             "#00BA38", "#00C19F", "#00B9E3",
#             "#619CFF", "#DB72FB"]
# df.plot(style='.', figsize=(15,5), color=color_pal[1], title='PJM East Delayed')
# plt.show()

"""## Running the Model"""

df['Datetime'].dt.hour

def create_features(df, label=None):
    """
    Creates time series features from datetime index.
    """
    df = df.copy()
    df['date'] = df.index
    df['date'] = pd.to_datetime(df['date'])
    print(df['date'].dtypes)
    df['hour'] = df['Datetime'].dt.hour
    df['dayofweek'] = df['Datetime'].dt.dayofweek
    df['quarter'] = df['Datetime'].dt.quarter
    df['month'] = df['Datetime'].dt.month
    df['year'] = df['Datetime'].dt.year
    df['dayofyear'] = df['Datetime'].dt.dayofyear
    df['dayofmonth'] = df['Datetime'].dt.day
    df['weekofyear'] = df['Datetime'].dt.weekofyear
    
    X = df[['hour','dayofweek','quarter','month','year',
           'dayofyear','dayofmonth','weekofyear']]
    if label:
        y = df[label]
        return X, y
    return X

X, y = create_features(df, label='PJME_MW')

features_and_target = pd.concat([X, y], axis=1)

# See our features and target
features_and_target.head()

"""Plotting the Features to see trends
1. Power demand has strong daily and seasonal properties.
2. Day of week also seems to show differences in peaks
"""

sns.pairplot(features_and_target.dropna(),
             hue='hour',
             x_vars=['hour','dayofweek',
                     'year','weekofyear'],
             y_vars='PJME_MW',
             height=5,
             plot_kws={'alpha':0.15, 'linewidth':0}
            )
plt.suptitle('Power Use MW by Hour, Day of Week, Year and Week of Year')
plt.show()

"""## Train/Test Split"""

df = df.set_index('Datetime')

#Splitting the Delayed dataset in terms of seconds
split_date = '01-Jan-2015'
pjme_train_delayed = df.loc[df.index <= split_date].copy()
pjme_test_delayed= df.loc[df.index > split_date].copy()

"""## ERROR Metrics"""

def mean_absolute_percentage_error(y_true, y_pred): 
    """Calculates MAPE given y_true and y_pred"""
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

"""## Simple Prophet Model

## Check on Delayed terms in milliseconds

Case 1: Train on Delayed and Test also on Delayed
"""

# Format data for prophet model using ds and y
pjme_train_delayed.reset_index() \
    .rename(columns={'Datetime':'ds',
                     'PJME_MW':'y'}).head()

# Setup and train model and fit
model = Prophet()
model.fit(pjme_train_delayed.reset_index() \
              .rename(columns={'Datetime':'ds',
                               'PJME_MW':'y'}))

# Predict on testing set with model (delayed Dataset)
pjme_test_fcst = model.predict(df=pjme_test_delayed.reset_index() \
                                   .rename(columns={'Datetime':'ds'}))

# Plot the forecast
f, ax = plt.subplots(1)
f.set_figheight(5)
f.set_figwidth(15)
fig = model.plot(pjme_test_fcst,
                 ax=ax)
plt.show()

mean_squared_error(y_true=pjme_test_delayed['PJME_MW'],
                   y_pred=pjme_test_fcst['yhat'])

mean_absolute_error(y_true=pjme_test_delayed['PJME_MW'],
                   y_pred=pjme_test_fcst['yhat'])

mean_absolute_percentage_error(y_true=pjme_test_delayed['PJME_MW'],
                   y_pred=pjme_test_fcst['yhat'])

